# Generated by Django 5.2.15 on 2026-07-01 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('texto', models.TextField()),
                ('imagem', models.ImageField(upload_to='posts/')),
                ('data_publicacao', models.DateField()),
            ],
        ),
    ]
